<?php

namespace App\Filament\Resources\AssetsResource\Pages;

use App\Filament\Resources\AssetsResource;
use Filament\Actions;
use Filament\Resources\Pages\ViewRecord;

class ViewAsset extends ViewRecord
{
    protected static string $resource = AssetsResource::class;

    public function getBreadcrumb(): string
    {
        return parent::getBreadcrumb(); // TODO: Change the autogenerated stub
    }


}
