<?php

namespace App\Filament\Resources\NetworkScannerResource\Pages;

use App\Filament\Resources\AssetsResource;
use App\Filament\Resources\NetworkScannerResource;
use Filament\Actions;
use Filament\Resources\Pages\ViewRecord;

class ViewNetworkScanner extends ViewRecord
{
    protected static string $resource = NetworkScannerResource::class;

    public function getBreadcrumb(): string
    {
        return parent::getBreadcrumb(); // TODO: Change the autogenerated stub
    }

    protected function getForms(): array
    {
        return parent::getForms(

        ); // TODO: Change the autogenerated stub
    }


}
